---
- name: Deploy app in new namespace
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /var/jenkins_home/workspace/Banking-capstone-project/Terraform/lke-cluster-config.yaml
    - name: Deploy Banking Finance Application on Kubernets cluster
      kubernetes.core.k8s:
        src: banking-deployment.yaml
        state: present
        namespace: test
        kubeconfig: /var/jenkins_home/workspace/Banking-capstone-project/Terraform/lke-cluster-config.yaml